/**
 * All Madhya Pradesh university names from `all_mp_university_details.json` (repo root).
 * Keep in sync when that list changes.
 * @type {readonly string[]}
 */
export const MP_UNIVERSITY_NAMES = Object.freeze([
  "A.K.S. University",
  "Abhyuday University",
  "Amaltas University",
  "Amity University",
  "Aryavart University",
  "Atal Bihari Vajpayee Hindi Vishwavidyalaya",
  "Avantika University",
  "Awadesh Pratap Singh University",
  "Azim Premji University",
  "Barkatullaah University",
  "Bhabha University",
  "Chirayu University",
  "Devi Ahilya Vishwavidyalaya",
  "Dharmashastra National Law University",
  "Dr C V Raman University",
  "Dr. A.P.J Abdul Kalam University",
  "Dr. B. R. Ambedkar University of Social Sciences",
  "Dr. Harisingh Gour Vishwavidyalaya,SAGAR",
  "Dr. Preeti Global University",
  "Eklavya University",
  "G.H Raisoni University",
  "Gyanodaya University",
  "Gyanveer University",
  "I.E.S. University",
  "Indian Institute of Forest Management (IIFM)",
  "ITM University",
  "J. N. C. T professional University",
  "Jagran Lakecity University",
  "Jawaharlal Nehru Krishi Vishwavidyalaya",
  "Jaypee University of Engineering & Technology",
  "Jiwaji University",
  "Krantisurya Tantya Bhil Vishwavidyalaya",
  "Krantivir Tatya Tope Vishwavidyalaya",
  "Lakshmibai National Institute of Physical Education",
  "LNCT UNIVERSITY BHOPAL",
  "LNCT Vidhyapeeth University",
  "M.P.Bhoj (open) University",
  "Madhav Institute of Technology and Science",
  "Madhya Pradesh Medical Science University",
  "Madhyanchal Professional University",
  "Mahakaushal University",
  "Maharaja Chhatrasal Bundelkhand Vishwavidyalaya",
  "Maharishi Mahesh Yogi Vedic Vishwavidyalaya",
  "Maharshi Panini Sanskrit Evam Vedic Vishwavidyalaya",
  "Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya",
  "Makhanlal Chaturvedi National University of Journalism & Communication",
  "Malwanchal University",
  "Mandsaur University",
  "Mangalayatan University",
  "Mansarovar Global University",
  "Medi-Caps University",
  "Nanaji Deshmukh Pashu Chikitsa Vigyan Vishwavidyalaya",
  "National Institute of Technical Teachers Training & Research (NITTTR)",
  "National Law Institute University",
  "Oriental University",
  "P.K. University",
  "Pandit S N Shukla University",
  "People's University",
  "Prestige Institute of Management and Research (PIMR)",
  "Prestige University",
  "Rabindranath Tagore University (formerly known as AISECT University)",
  "Raja Mansingh Tomar Music & Arts University",
  "Rajiv Gandhi Prodoyogiki Vishwavidyalaya (UG-PG)",
  "Raja Shankar Shah University, Chhindwara",
  "Rajiv Gandhi Prodoyogiki Vishwavidyalaya (DIPLOMA WINGS)",
  "Rani Awantibai Lodhi Vishwavidyalaya",
  "Rajmata Vijayaraje Scindia Krishi Vishwa Vidyalaya",
  "Rani Durgavati Vishwavidyalaya",
  "Renaissance University",
  "RKDF University",
  "Sage University",
  "SAM Global University",
  "Sanchi University of Buddhist-Indic Studies",
  "Sanjeev Agrawal Global Educational University",
  "Sardar Patel University",
  "Sarvepalli Radhakrishnan University",
  "Scope Global Skills University",
  "Shri Krishna University",
  "Shri Vaishnav Vidyapeeth Vishwavidyalaya",
  "Shubham University",
  "Sri Aurobindo University",
  "Sri Satya Sai University of Technology & Medical Sciences",
  "Swami Vivekanand University",
  "Symbiosis University of Applied Sciences (SUAS)",
  "Techno Global University",
  "The Indira Gandhi National Tribal University",
  "Vikram University",
  "Vikrant University",
  "VIT Bhopal University"
]);

/** @type {number} */
export const MP_UNIVERSITY_COUNT = MP_UNIVERSITY_NAMES.length;
